### ISSUE TITLE
compute_fbank 中 dither 是设置0还是1？

### ISSUE THREAD

**Issue by zuowanbushiwo** [wenet-e2e/wespeaker#234]
1. 我看训练的时候设置的是dither: 1.0
dataset_args:
```
  aug_prob: 0.6
  fbank_args:
    dither: 1.0
    frame_length: 25
    frame_shift: 10
    num_mel_bins: 80
```
2. 在infer_onnx.py 中又是dither: 0.0
3. 在C++ onnxruntime 中 设置的dither: 0.0
4. 在这里 https://github.com/wenet-e2e/wespeaker/blob/a84bd7dd63758781af317f587323bb8542157d0a/runtime/server/x86_gpu/model_repo/feature_extractor/1/model.py#L69  又设置 dither: 1

这个变量对结果没什么影响吗？

> - dither的作用  
> dither为1，作用是在计算滤波器系数能量时加入随机扰动，防止能量为0的情况出现，会导致同一条音频的输出特征前后不一致。如果需要保持一致，要在配置文件中设置dither=0

谢谢！
